name: AI
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
concurrency:
  group: ai
  cancel-in-progress: true
jobs:
  ai:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Placeholder
        run: echo "[OK] AI Placeholder Running"
