name: Build
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run Placeholder
        run: echo "[OK] Build Workflow Running"
