name: Build
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.150.1'
          extended: true

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install NPM packages
        run: npm ci

      - name: Run Hugo Build
        shell: bash
        run: |
          hugo --minify
          echo "[OK] Hugo build finished"

      - name: Save Build Logs
        run: |
          echo "Build completed at $(date)" >> build_log.txt
          du -sh public >> build_log.txt

      - uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: build_log.txt
