name: Build
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
concurrency:
  group: build
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Placeholder
        run: echo "[OK] Build Placeholder Running"
