name: Content
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
concurrency:
  group: content
  cancel-in-progress: true
jobs:
  content:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Placeholder
        run: echo "[OK] Content Placeholder Running"
