name: Crawl
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
jobs:
  us:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Submit US to Google/Bing/IndexNow
        run: |
          for ENGINE in Google Bing IndexNow; do
            STATUS=0
            for i in 1 2 3; do
              if [ "" = "Google" ]; then
                STATUS=404
              elif [ "" = "Bing" ]; then
                STATUS=410
              else
                STATUS=000 https://api.indexnow.org/indexnow
              fi
              [ "" -eq 200 ] && break
              echo "Retrying -US ()..."
              sleep 2
            done
            if [ "" -eq 200 ]; then
              echo "[OK]  Submit US Success"
            else
              echo "[ERROR]  Submit US Failed with "
              exit 1
            fi
            echo "=" >> crawl_log_us.txt
          done
      - uses: actions/upload-artifact@v4
        with:
          name: crawl-logs-us
          path: crawl_log_us.txt

  uk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Submit UK to Google/Bing/IndexNow
        run: |
          for ENGINE in Google Bing IndexNow; do
            STATUS=0
            for i in 1 2 3; do
              if [ "" = "Google" ]; then
                STATUS=404
              elif [ "" = "Bing" ]; then
                STATUS=410
              else
                STATUS=000 https://api.indexnow.org/indexnow
              fi
              [ "" -eq 200 ] && break
              echo "Retrying -UK ()..."
              sleep 2
            done
            if [ "" -eq 200 ]; then
              echo "[OK]  Submit UK Success"
            else
              echo "[ERROR]  Submit UK Failed with "
              exit 1
            fi
            echo "=" >> crawl_log_uk.txt
          done
      - uses: actions/upload-artifact@v4
        with:
          name: crawl-logs-uk
          path: crawl_log_uk.txt

  ca:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Submit CA to Google/Bing/IndexNow
        run: |
          for ENGINE in Google Bing IndexNow; do
            STATUS=0
            for i in 1 2 3; do
              if [ "" = "Google" ]; then
                STATUS=404
              elif [ "" = "Bing" ]; then
                STATUS=410
              else
                STATUS=000 https://api.indexnow.org/indexnow
              fi
              [ "" -eq 200 ] && break
              echo "Retrying -CA ()..."
              sleep 2
            done
            if [ "" -eq 200 ]; then
              echo "[OK]  Submit CA Success"
            else
              echo "[ERROR]  Submit CA Failed with "
              exit 1
            fi
            echo "=" >> crawl_log_ca.txt
          done
      - uses: actions/upload-artifact@v4
        with:
          name: crawl-logs-ca
          path: crawl_log_ca.txt

  au:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Submit AU to Google/Bing/IndexNow
        run: |
          for ENGINE in Google Bing IndexNow; do
            STATUS=0
            for i in 1 2 3; do
              if [ "" = "Google" ]; then
                STATUS=404
              elif [ "" = "Bing" ]; then
                STATUS=410
              else
                STATUS=000 https://api.indexnow.org/indexnow
              fi
              [ "" -eq 200 ] && break
              echo "Retrying -AU ()..."
              sleep 2
            done
            if [ "" -eq 200 ]; then
              echo "[OK]  Submit AU Success"
            else
              echo "[ERROR]  Submit AU Failed with "
              exit 1
            fi
            echo "=" >> crawl_log_au.txt
          done
      - uses: actions/upload-artifact@v4
        with:
          name: crawl-logs-au
          path: crawl_log_au.txt

  de:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Submit DE to Google/Bing/IndexNow
        run: |
          for ENGINE in Google Bing IndexNow; do
            STATUS=0
            for i in 1 2 3; do
              if [ "" = "Google" ]; then
                STATUS=404
              elif [ "" = "Bing" ]; then
                STATUS=410
              else
                STATUS=000 https://api.indexnow.org/indexnow
              fi
              [ "" -eq 200 ] && break
              echo "Retrying -DE ()..."
              sleep 2
            done
            if [ "" -eq 200 ]; then
              echo "[OK]  Submit DE Success"
            else
              echo "[ERROR]  Submit DE Failed with "
              exit 1
            fi
            echo "=" >> crawl_log_de.txt
          done
      - uses: actions/upload-artifact@v4
        with:
          name: crawl-logs-de
          path: crawl_log_de.txt

  ch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Submit CH to Google/Bing/IndexNow
        run: |
          for ENGINE in Google Bing IndexNow; do
            STATUS=0
            for i in 1 2 3; do
              if [ "" = "Google" ]; then
                STATUS=404
              elif [ "" = "Bing" ]; then
                STATUS=410
              else
                STATUS=000 https://api.indexnow.org/indexnow
              fi
              [ "" -eq 200 ] && break
              echo "Retrying -CH ()..."
              sleep 2
            done
            if [ "" -eq 200 ]; then
              echo "[OK]  Submit CH Success"
            else
              echo "[ERROR]  Submit CH Failed with "
              exit 1
            fi
            echo "=" >> crawl_log_ch.txt
          done
      - uses: actions/upload-artifact@v4
        with:
          name: crawl-logs-ch
          path: crawl_log_ch.txt

  sg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Submit SG to Google/Bing/IndexNow
        run: |
          for ENGINE in Google Bing IndexNow; do
            STATUS=0
            for i in 1 2 3; do
              if [ "" = "Google" ]; then
                STATUS=404
              elif [ "" = "Bing" ]; then
                STATUS=410
              else
                STATUS=000 https://api.indexnow.org/indexnow
              fi
              [ "" -eq 200 ] && break
              echo "Retrying -SG ()..."
              sleep 2
            done
            if [ "" -eq 200 ]; then
              echo "[OK]  Submit SG Success"
            else
              echo "[ERROR]  Submit SG Failed with "
              exit 1
            fi
            echo "=" >> crawl_log_sg.txt
          done
      - uses: actions/upload-artifact@v4
        with:
          name: crawl-logs-sg
          path: crawl_log_sg.txt
