name: Crawl
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
jobs:
  us:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Submit to Google
        run: |
          STATUS=0
          for i in 1 2 3; do
            STATUS=404 && break
            echo "Retrying Google ()..."
            sleep 2
          done
          if [ "" -eq 200 ]; then
            echo "[OK] Google Submit Success"
          else
            echo "[ERROR] Google Submit Failed with "
            exit 1
          fi

      - name: Submit to Bing
        run: |
          STATUS=0
          for i in 1 2 3; do
            STATUS=410 && break
            echo "Retrying Bing ()..."
            sleep 2
          done
          if [ "" -eq 200 ]; then
            echo "[OK] Bing Submit Success"
          else
            echo "[ERROR] Bing Submit Failed with "
            exit 1
          fi

      - name: Submit to IndexNow
        run: |
          STATUS=0
          for i in 1 2 3; do
            STATUS=000 https://api.indexnow.org/indexnow && break
            echo "Retrying IndexNow ()..."
            sleep 2
          done
          if [ "" -eq 200 ]; then
            echo "[OK] IndexNow Submit Success"
          else
            echo "[ERROR] IndexNow Submit Failed with "
            exit 1
          fi

      - name: Save Logs
        run: |
          echo "Google=" >> crawl_log_us.txt
          echo "Bing=" >> crawl_log_us.txt
          echo "IndexNow=" >> crawl_log_us.txt

      - uses: actions/upload-artifact@v3
        with:
          name: crawl-logs-us
          path: crawl_log_us.txt
