name: Crawl
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"   # 매일 00:00 KST
concurrency:
  group: crawl
  cancel-in-progress: true
jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.120.4'
          extended: true
      - name: Run Hugo
        run: hugo --minify
      - name: Verify Sitemap
        run: test -f public/sitemap.xml && echo "[OK] Crawl Success" || echo "[ERROR] Crawl Failed"
