name: Crawl
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
jobs:
  us:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Submit US to Google
        run: |
          STATUS=0
          for i in 1 2 3; do
            STATUS=404 && break
            echo "Retrying Google-US ()..."
            sleep 2
          done
          if [ "" -eq 200 ]; then
            echo "[OK] Google Submit US Success"
          else
            echo "[ERROR] Google Submit US Failed with "
            exit 1
          fi
      - name: Submit US to Bing
        run: |
          STATUS=0
          for i in 1 2 3; do
            STATUS=410 && break
            echo "Retrying Bing-US ()..."
            sleep 2
          done
          if [ "" -eq 200 ]; then
            echo "[OK] Bing Submit US Success"
          else
            echo "[ERROR] Bing Submit US Failed with "
            exit 1
          fi
      - name: Submit US to IndexNow
        run: |
          STATUS=0
          for i in 1 2 3; do
            STATUS=000 https://api.indexnow.org/indexnow && break
            echo "Retrying IndexNow-US ()..."
            sleep 2
          done
          if [ "" -eq 200 ]; then
            echo "[OK] IndexNow Submit US Success"
          else
            echo "[ERROR] IndexNow Submit US Failed with "
            exit 1
          fi
      - name: Save US Logs
        run: |
          echo "Google=" >> crawl_log_us.txt
          echo "Bing=" >> crawl_log_us.txt
          echo "IndexNow=" >> crawl_log_us.txt
      - uses: actions/upload-artifact@v3
        with:
          name: crawl-logs-us
          path: crawl_log_us.txt

  uk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Submit UK to Google
        run: curl -X POST "https://www.google.com/ping?sitemap=https://newspreadnow.com/uk/sitemap.xml"
      - name: Submit UK to Bing
        run: curl -X GET "https://www.bing.com/ping?sitemap=https://newspreadnow.com/uk/sitemap.xml"
      - name: Submit UK to IndexNow
        run: |
          curl -H 'Content-Type: application/json' \
          -d '{"host":"newspreadnow.com","urlList":["https://newspreadnow.com/uk/sitemap.xml"]}' \
          "https://api.indexnow.org/indexnow"

  ca:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Submit CA to Google
        run: curl -X POST "https://www.google.com/ping?sitemap=https://newspreadnow.com/ca/sitemap.xml"
      - name: Submit CA to Bing
        run: curl -X GET "https://www.bing.com/ping?sitemap=https://newspreadnow.com/ca/sitemap.xml"
      - name: Submit CA to IndexNow
        run: |
          curl -H 'Content-Type: application/json' \
          -d '{"host":"newspreadnow.com","urlList":["https://newspreadnow.com/ca/sitemap.xml"]}' \
          "https://api.indexnow.org/indexnow"

  au:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Submit AU to Google
        run: curl -X POST "https://www.google.com/ping?sitemap=https://newspreadnow.com/au/sitemap.xml"
      - name: Submit AU to Bing
        run: curl -X GET "https://www.bing.com/ping?sitemap=https://newspreadnow.com/au/sitemap.xml"
      - name: Submit AU to IndexNow
        run: |
          curl -H 'Content-Type: application/json' \
          -d '{"host":"newspreadnow.com","urlList":["https://newspreadnow.com/au/sitemap.xml"]}' \
          "https://api.indexnow.org/indexnow"

  de:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Submit DE to Google
        run: curl -X POST "https://www.google.com/ping?sitemap=https://newspreadnow.com/de/sitemap.xml"
      - name: Submit DE to Bing
        run: curl -X GET "https://www.bing.com/ping?sitemap=https://newspreadnow.com/de/sitemap.xml"
      - name: Submit DE to IndexNow
        run: |
          curl -H 'Content-Type: application/json' \
          -d '{"host":"newspreadnow.com","urlList":["https://newspreadnow.com/de/sitemap.xml"]}' \
          "https://api.indexnow.org/indexnow"

  ch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Submit CH to Google
        run: curl -X POST "https://www.google.com/ping?sitemap=https://newspreadnow.com/ch/sitemap.xml"
      - name: Submit CH to Bing
        run: curl -X GET "https://www.bing.com/ping?sitemap=https://newspreadnow.com/ch/sitemap.xml"
      - name: Submit CH to IndexNow
        run: |
          curl -H 'Content-Type: application/json' \
          -d '{"host":"newspreadnow.com","urlList":["https://newspreadnow.com/ch/sitemap.xml"]}' \
          "https://api.indexnow.org/indexnow"

  sg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Submit SG to Google
        run: curl -X POST "https://www.google.com/ping?sitemap=https://newspreadnow.com/sg/sitemap.xml"
      - name: Submit SG to Bing
        run: curl -X GET "https://www.bing.com/ping?sitemap=https://newspreadnow.com/sg/sitemap.xml"
      - name: Submit SG to IndexNow
        run: |
          curl -H 'Content-Type: application/json' \
          -d '{"host":"newspreadnow.com","urlList":["https://newspreadnow.com/sg/sitemap.xml"]}' \
          "https://api.indexnow.org/indexnow"
