name: Crawl
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - name: Run Placeholder
        run: echo "[OK] Crawl Workflow Running"
