name: Crawl
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
concurrency:
  group: crawl
  cancel-in-progress: true
jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Placeholder
        run: echo "[OK] Crawl Placeholder Running"
