name: Deploy
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Run Placeholder
        run: echo "[OK] Deploy Workflow Running"
