name: Deploy
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
jobs:
  us:
    runs-on: ubuntu-latest
    steps:
      - name: US Deploy
        run: echo "[OK] Deploy Workflow - US"
  uk:
    runs-on: ubuntu-latest
    steps:
      - name: UK Deploy
        run: echo "[OK] Deploy Workflow - UK"
  ca:
    runs-on: ubuntu-latest
    steps:
      - name: CA Deploy
        run: echo "[OK] Deploy Workflow - CA"
  au:
    runs-on: ubuntu-latest
    steps:
      - name: AU Deploy
        run: echo "[OK] Deploy Workflow - AU"
  de:
    runs-on: ubuntu-latest
    steps:
      - name: DE Deploy
        run: echo "[OK] Deploy Workflow - DE"
  ch:
    runs-on: ubuntu-latest
    steps:
      - name: CH Deploy
        run: echo "[OK] Deploy Workflow - CH"
  sg:
    runs-on: ubuntu-latest
    steps:
      - name: SG Deploy
        run: echo "[OK] Deploy Workflow - SG"
