name: Deploy
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
concurrency:
  group: deploy
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.120.4'
          extended: true
      - name: Build Site
        run: hugo --minify
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: site
          path: public
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: site
          path: ./public
      - name: Deploy Check
        run: test -f public/index.html && echo "[OK] Deploy Ready" || echo "[ERROR] Deploy Failed"
