name: Discover
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
jobs:
  discover:
    runs-on: ubuntu-latest
    steps:
      - name: Run Placeholder
        run: echo "[OK] Discover Workflow Running"
