name: Discover
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
concurrency:
  group: discover
  cancel-in-progress: true
jobs:
  discover:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Placeholder
        run: echo "[OK] Discover Placeholder Running"
