name: GSC Submit
on:
  workflow_dispatch:
  schedule:
    - cron: "15 0 * * *"
concurrency:
  group: gsc
  cancel-in-progress: true
jobs:
  submit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Run GSC Submit
        run: python scripts/gsc_submit.py
