name: Deploy Hugo site to Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.150.1'
          extended: true

      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - run: npm install postcss postcss-cli autoprefixer

      - run: |
          mkdir -p content/posts
          echo "---`ntitle: 'First'`ndate: 2025-10-01T00:00:00Z`ndraft: false`n---`nHello Hugo!" > content/posts/first.md

      - run: hugo --gc --minify --cleanDestinationDir

      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
