name: IndexNow Submit
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
jobs:
  submit:
    runs-on: ubuntu-latest
    steps:
      - name: Submit sitemap to IndexNow
        run: |
          curl -X POST "https://api.indexnow.org/IndexNow" \
            -H 'Content-Type: application/json' \
            -d "{
              \"host\": \"newspreadnow.com\",
              \"key\": \"${{ secrets.INDEXNOW_KEY }}\",
              \"keyLocation\": \"https://newspreadnow.com/${{ secrets.INDEXNOW_KEY }}.txt\",
              \"urlList\": [\"https://newspreadnow.com/sitemap.xml\"]
            }"
