name: SEO
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
concurrency:
  group: seo
  cancel-in-progress: true
jobs:
  seo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Placeholder
        run: echo "[OK] SEO Placeholder Running"
